# Set the version of docker compose to use
version: "3.9"

# The containers that compose the project
services:
  node-app:
    build: .
    image: node-app
    environment:
      - DATABASE_URL=postgresql://prisma:prisma@localhost:5433/db
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network
  db:
    image: postgres:13
    restart: always
    container_name: postgres-prisma
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: db

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
