[build.environment]
  NPM_FLAGS = "--version"
[build]
  command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"
[[plugins]]
  package = "./plugins/pnpm-preinstaller"
[[plugin]]
  package = "@netlify/plugin-nextjs"