[build.environment]
  NPM_FLAGS = "--version"

[build]
  base = "packages/builder/"
  command = "npx pnpm build --filter @open-decision/frontend..."
  publish = ".next/"

[[plugins]]
  package = "../../plugins/pnpm-preinstaller"

[[plugins]]
  package = "@sentry/netlify-build-plugin"
  [plugins.inputs]
    sentryOrg = "open-legal-tech-ev"
    sentryProject = "builder"