name: Cleanup PR Deploys
on:
  pull_request:
    types: [closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  remove_api_deploy:
    runs-on: ubuntu-latest
    name: Remove API Deploy

    env:
      APP_NAME: ${{format('pr-{0}-open-decision', github.event.pull_request.number)}}
      DB_NAME: ${{format('pr-{0}-open-decision-db', github.event.pull_request.number)}}

    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Remove API Deploy
        continue-on-error: true
        run: flyctl apps destroy ${{env.APP_NAME}} --yes

  remove_builder_deploy:
    runs-on: ubuntu-latest
    name: Remove Builder Deploy

    env:
      OD_BUILDER_ENDPOINT: ${{format('open-decision-{0}.vercel.app', github.event.pull_request.number)}}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install Vercel CLI
        run: yarn add global vercel@latest

      - name: Remove api endpoint end var
        continue-on-error: true
        run: vercel env rm NEXT_PUBLIC_OD_API_ENDPOINT preview ${{ github.head_ref }} --token ${{secrets.VERCEL_TOKEN}} --yes || true

      - name: Remove od app endpoint end var
        continue-on-error: true
        run: vercel env rm NEXT_PUBLIC_OD_BUILDER_ENDPOINT preview ${{ github.head_ref }} --token ${{secrets.VERCEL_TOKEN}} --yes

      - name: Remove api websocket endpoint env var
        continue-on-error: true
        run: vercel env rm NEXT_PUBLIC_OD_WEBSOCKET_ENDPOINT preview ${{ github.head_ref }} --token ${{secrets.VERCEL_TOKEN}} --yes

      - name: Remove Builder Deploy
        continue-on-error: true
        run: vercel alias rm ${{env.OD_BUILDER_ENDPOINT}} --token ${{secrets.VERCEL_TOKEN}} --scope open-decision --yes
